In [1]:
import numpy as np

# observed feature frequencies, per class, i.e. the contingency table

Labels = $\left[K_0 \quad \dots \quad K_n \right] $ mit n = Anzahl der Daten

Y = $\left(\begin{array}{Y} 1 - Labels \\ Labels \end{array}\right) $

$O_{cf}$

c - Labels index

f - Feature index

X = \begin{bmatrix}
 O_{11}      & \cdots & O_{1n}  \\
 O_{21}      & \cdots &  O_{2n} \\
\end{bmatrix}

B = $Y \cdot X$

$L_{M}$ = Anzahl der Merkmale

$M_{c}$ = $\left [ \sum_{n=1}^2O_{n1} \quad \dots \quad \sum_{n=1}^{2}O_{nL_{M}}  \right ]$

$C_{p}$ = $\left [ \frac{1}{L_{M}}\sum_{n=1}^{L_{M}}O_{1n} \qquad \frac{1}{L_{M}}\sum_{n=1}^{L_{M}}O_{2n}   \right ] $   Durchschnitt von Labels auf y-Achse

E = $ (M_{c} \cdot C_{p})^T$

In [43]:
print(feature_count.reshape(-1, 1))
print()
print(class_prob.reshape(1, -1))
print()
print(np.dot(feature_count.reshape(-1, 1), class_prob.reshape(1, -1)))

[[2]
 [1]
 [6]
 [1]
 [2]]

[[ 0.5  0.5]]

[[ 1.   1. ]
 [ 0.5  0.5]
 [ 3.   3. ]
 [ 0.5  0.5]
 [ 1.   1. ]]


In [174]:
y = np.array([1, 0, 1])
X = np.array([[1, 0, 2, 0, 1], [1, 1, 4, 1, 1], [1, 0, 2, 0, 1]])

In [175]:
Y = np.vstack([1 - y, y])
print(Y)

[[0 1 0]
 [1 0 1]]


In [176]:
observed = np.dot(Y, X) # Skalarprodukt
print(observed)

[[1 1 4 1 1]
 [2 0 4 0 2]]


# Expected value

In [177]:
feature_count = X.sum(axis=0)
class_prob = Y.mean(axis=1)
expected = np.dot(feature_count.reshape(-1, 1), class_prob.reshape(1, -1)).T

In [178]:
print(Y[0])
print(Y[1])

print(Y.mean(axis=1))

[0 1 0]
[1 0 1]
[ 0.33333333  0.66666667]


In [179]:
print(feature_count)

[3 1 8 1 3]


In [180]:
print(class_prob)

[ 0.33333333  0.66666667]


In [181]:
print(expected)

[[ 1.          0.33333333  2.66666667  0.33333333  1.        ]
 [ 2.          0.66666667  5.33333333  0.66666667  2.        ]]


# X-square

In [186]:
from scipy.stats import chisquare
print("Observed", observed)
print()
print("Expected:", expected)
print()
score, pval = chisquare(observed, expected)
print(score)
print(pval)

Observed [[1 1 4 1 1]
 [2 0 4 0 2]]

Expected: [[ 1.          0.33333333  2.66666667  0.33333333  1.        ]
 [ 2.          0.66666667  5.33333333  0.66666667  2.        ]]

[ 0.  2.  1.  2.  0.]
[ 1.          0.15729921  0.31731051  0.15729921  1.        ]
