In [1]:
import numpy as np

A = Datamatrix

In [3]:
A = np.array([[ 3, 0, 3],
              [ 5, 4, 0],
              [ 1, 2, 4],
              [ 2, 2, 0]])

In [13]:
U_values,U = np.linalg.eig(np.dot(A, np.transpose(A)))
print(U)

[[-0.415103   -0.4754462   0.76791353  0.10931247]
 [-0.74371645  0.52779221 -0.01689327 -0.40992176]
 [-0.41095874 -0.66262863 -0.62073729 -0.08198435]
 [-0.3250973   0.23729643 -0.15718985  0.90182787]]


In [21]:
V_values,V = np.linalg.eig(np.dot(np.transpose(A), A))
print(V)
print()
V_t = np.transpose(V)
print(V_t)

[[-0.75064858 -0.61807715 -0.2334681 ]
 [-0.55404032  0.78137107 -0.28722565]
 [-0.35995283  0.08625479  0.92897474]]

[[-0.75064858 -0.55404032 -0.35995283]
 [-0.61807715  0.78137107  0.08625479]
 [-0.2334681  -0.28722565  0.92897474]]


In [29]:
print(V_values)

[ 64.42392746   4.31669193  19.25938061]


In [28]:
S = np.diag(np.sqrt(-np.sort(-V_values)))
print(S)

[[ 8.02645174  0.          0.        ]
 [ 0.          4.38855108  0.        ]
 [ 0.          0.          2.07766502]]
